#' CTCF Peaks
#'
#' A set of CTCF TIP-seq peaks (narrowPeak) produced by MACS3 (first-mate only,
#' 5'-shift to centre the 5' end of each read). The BAM file used as input for
#' peak calling was generated by Bartlett et al. (2021) and retrieved from NCBI
#' GEO under accession GSE188512. Specifically, we used GSM5684367	(CTCF
#' TIP-seq 5k cells). The peak file has been subset to reduce the data size
#' (only chromosome 19).
#'
#' The code used to prepare the data as an .rda file is:
#'
#' \code{ctcf_peaks <- read.table("path/to/ctcf_peaks")} \cr
#' \code{ctcf_peaks <- ctcf_peaks[ctcf_peaks$V1 == "chr19",]} \cr
#' \code{write.table(ctcf_peaks,
#'                   "inst/extdata/ctcf_subset.narrowPeak",
#'                   row.names = FALSE,
#'                   col.names = FALSE,
#'                   quote = FALSE,
#'                   sep = "\t")} \cr
#' \code{ctcf_peaks <- read_peak_file("inst/extdata/ctcf_subset.narrowPeak")} \cr
#' \code{usethis::use_data(ctcf_peaks, overwrite = TRUE)} \cr
#'
#' @format A GRanges peak object outputted by the \code{read_peak_file}
#' function.
#' @source NCBI GEO (GSE188512)
#' \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE188512}
#' @usage data("ctcf_peaks")
"ctcf_peaks"
