#' Calculate motif enrichment in a set of sequences
#'
#' \code{motif_enrichment()} calculates motif enrichment relative to a set of
#' background sequences using Analysis of Motif Enrichment (AME) from
#' \link{memes}.
#'
#' @importFrom memes runAme
#' @importFrom utils read.table
#' @import GenomicRanges
#'
#' @param peak_input Either a path to the narrowPeak file or a GRanges peak
#' object generated by \code{read_peak_file()}.
#' @param motif An object of class \code{PWMatrix}.
#' @param genome_build The genome build that the peak sequences should be
#' derived from.
#' @param out_dir Location to save the 0-order background file along with the
#' AME output files.
#' @inheritDotParams memes::runAme -input -control -outdir -database
#'
#' @returns A list containing a FIMO results data frame and a numeric referring
#' to the proportion of peaks with a motif.
#'
#' @examples
#' \dontrun{
#' peak_file <- system.file("extdata",
#'                          "rep1_peaks.narrowPeak",
#'                          package = "MotifStats"
#'                          )
#' data("creb_motif", package = "MotifStats")
#'
#' motif_enrichment(
#'   peak_input = peak_file,
#'   motif = creb_motif,
#'   genome_build = BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38,
#'   out_dir = "./"
#' )
#' }
#'
#' @seealso \link[memes]{runAme}
#' @export
motif_enrichment <- function(peak_input,
                             motif,
                             genome_build,
                             out_dir = tempdir(),
                             ...) {
  peaks_and_seqs <- check_peak_input(peak_input = peak_input,
                                     genome_build = genome_build)
  peaks <- peaks_and_seqs[[1]] # 1st position of peaks_and_seqs vector
  peak_sequences <- peaks_and_seqs[[2]] # 2nd position of peaks_and_seqs vector

  # Generate 0-order background model from the input sequences
  bfile <- markov_background_model(sequences = peak_sequences,
                                   out_dir = out_dir)
  ame_out <- memes::runAme(peak_sequences,
                           database = list(motif),
                           outdir = out_dir)

  seq_path <- file.path(out_dir, "sequences.tsv")
  seq <- utils::read.table(seq_path, header = TRUE)
  cleaned_ids <- seq$seq_ID[!grepl("_shuf_1", seq$seq_ID)]

  return(
    list(
      tp = c(ame_out$tp, ame_out$tp_percent),
      fp = c(ame_out$fp, ame_out$fp_percent),
      positive_peaks = peaks[cleaned_ids]
    )
  )
}
