#' Calculate the proportion of peaks with a motif
#'
#' \code{peak_proportion()} calculates the proportion of peaks containing a
#' motif relative to a set of background sequences using Find Individual Motif
#' Occurrences (FIMO) from \link[memes].
#'
#' @importFrom memes runFimo
#' @import GenomicRanges
#'
#' @param peak_input Either a path to the narrowPeak file or a GRanges peak
#' object generated by \code{read_peak_file()}.
#' @param pwm An object of class \code{PWMatrix}.
#' @param fp_rate False-positive rate to be used to calculate an appropriate
#' p-value threshold,
#' @param genome_build The genome build that the peak sequences should be
#' derived from.
#'
#' @returns A list containing a FIMO results data frame and a numeric referring
#' to the proportion of peaks with a motif.
#'
#' @examples
#' \dontrun{
#' peak_file <- system.file("extdata",
#'                          "rep1_peaks.narrowPeak",
#'                          package = "MotifStats"
#'                          )
#' data("creb_motif", package = "MotifStats")
#'
#' peak_proportion(
#'   peak_input = peak_file,
#'   motif = creb_motif,
#'   fp_rate = 5e-02,
#'   genome_build = BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38,
#' )
#' }
#'
#' @seealso \link[memes]{runFimo}
#' @export
peak_proportion <- function(peak_input,
                            motif,
                            fp_rate = 5e-02,
                            genome_build) {
  peaks_and_seqs <- check_peak_input(peak_input = peak_input,
                                     genome_build = genome_build)
  peaks <- peaks_and_seqs[[1]] # 1st position of peaks_and_seqs vector
  peak_sequences <- peaks_and_seqs[[2]] # 2nd position of peaks_and_seqs vector

  fimo_threshold <- fp_rate / (2 * mean(GenomicRanges::width(peaks)))
  messager("The p-value threshold for motif scanning with FIMO is",
           fimo_threshold)
  fimo_df <- memes::runFimo(peak_sequences,
                            motifs = motif,
                            thresh = fimo_threshold,
                            text = FALSE)
  names(fimo_df) <- GenomicRanges::seqnames(fimo_df)
  onehit_peak_names <- unique(names(fimo_df))
  onehit_peaks <- peak_sequences[names(peak_sequences) %in% onehit_peak_names, ]

  return(
    list(
      fimo_results = fimo_df,
      proportion_1_motif = length(onehit_peaks) / length(peaks)
    )
  )
}
